# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /app

COPY config/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

WORKDIR /app/run

CMD [ "python3", "app.py"]